version: '3'

services:

  ##############
  # swagger-ui #
  ##############
  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/
    restart: always

  # ##################
  # # postgrest-demo #
  # ##################
  # postgrest-demo:
  #   container_name: postgrest-demo
  #   image: nginx:mainline-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     # anything in html directory is hosted via nginx
  #     - "./html:/usr/share/nginx/html"
  #   restart: always